import AppStore from "@/app/userContext";

export const metadata = {
  title: "Join ",
  description: "Generated by Next.js",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppStore>

        {children}
        </AppStore>
      </body>
    </html>
  );
}
